services:
  - type: web
    name: rental-system
    env: java
    plan: free
    rootDir: rental-system
    buildCommand: "java -jar .mvn/wrapper/maven-wrapper.jar package -Dpackaging=jar"
    startCommand: "java -jar target/rental-system-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_VERSION
        value: 17